# Generated by Django 5.1.7 on 2025-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_options_payments_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.IntegerField(
                blank=True, max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
