# Generated by Django 5.1.7 on 2025-03-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
    ]
